openapi: "3.1.0"
info:
  x-logo:
    url: "https://avatars.githubusercontent.com/u/72045151?s=400&u=2da454a65a925719805331f9e3993bec4bc0b417&v=4"
  title: Pizzi API - Authorization server
  version: "pre-alpha"
  description: >
    This is the internal API authorization server documentation for the
    PizziPayment.
    You can find out more about Pizzi [here](https://www.pizzi-payment.fr).
  contact:
    email: contact@pizzi-payment.fr

servers:
  - description: localhost
    url: http://localhost:5000

tags:
  - name: Auth
    description: Everything about authentication.

paths:
  /login:
    $ref: './components/endpoints/login.yaml'

  /logout:
    $ref: './components/endpoints/logout.yaml'

components:
  schemas:
    # Requests
    RequestPasswordGrant:
      $ref: './components/schemas/requests/grant_types/password.yaml'
    RequestRefreshTokenGrant:
      $ref: './components/schemas/requests/grant_types/refresh_token.yaml'

    # Responses
    ResponseToken:
      $ref: './components/schemas/responses/token.yaml'

    ResponseError:
      $ref: './components/schemas/responses/error.yaml'

  examples:
    # Requests
    RequestPasswordGrant:
      $ref: './components/examples/requests/grant_types/password.yaml'
    RequestRefreshTokenGrant:
      $ref: './components/examples/requests/grant_types/refresh_token.yaml'

    # Responses
    ResponseError:
      $ref: './components/examples/responses/error.yaml'
    ResponseToken:
      $ref: './components/examples/responses/token.yaml'

  responses:
    200Token:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseToken'
          examples:
            Token:
              $ref: '#/components/examples/ResponseToken'

    400BadRequest:
      description: BAD REQUEST
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            Error:
              $ref: '#/components/examples/ResponseError'
    401Unauthorized:
      description: UNAUTHORIZED
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            Error:
              $ref: '#/components/examples/ResponseError'
    '500':
      description: INTERNAL SERVER ERROR
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ResponseError'
          examples:
            Error:
              $ref: '#/components/examples/ResponseError'

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer <token>

    BasicAuth:
      description: "Authorization: Basic <clientID:clientSecret b64>"
      type: http
      scheme: basic
