openapi: "3.0.2"
info:
  x-logo:
    url: "https://avatars.githubusercontent.com/u/72045151?s=400&u=2da454a65a925719805331f9e3993bec4bc0b417&v=4"
  title: Pizzi API - Authorization server
  version: "pre-alpha"
  description: >
    This is the internal API authorization server documentation for the
    PizziPayment.
    You can find out more about Pizzi [here](https://www.pizzi-payment.fr).
  contact:
    email: contact@pizzi-payment.fr

servers:
  - description: localhost
    url: http://localhost:5000

tags:
  - name: Auth
    description: Everything about authentication.

paths:
  /user/login:
    $ref: './components/endpoints/authentication/login_user.yaml'
  /shop/login:
    $ref: './components/endpoints/authentication/login_shop.yaml'
  /logout:
    $ref: './components/endpoints/authentication/logout.yaml'

components:
  securitySchemes:
    $ref: './components/security/_index.yaml'
