name: Documentation check & deploy
on:
  push:
    paths:
      - documentation/**

jobs:
  check-doc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./documentation
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install documentation tools
        run: yarn install
      - name: Linter
        run: yarn run linter
      - name: Builder
        run: yarn run builder

  trigger-doc-build:
    if: github.ref_name == 'master'
    needs: check-doc
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch action to deploy the documentation
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: PizziPayment/PizziPayment.github.io
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: Trigger authorization-server documentation build workflow
          client-payload: '{ "repo": "authorization-server" }'
